### ISSUE TITLE
Muncul history transaksi dobel

### ISSUE THREAD

**Issue by anvie** [nusantarachain/arascan#53]
Kasus:
https://scan.nuchain.network/account/5CFfC5N2pxxc682ges74CJrbQmM5UzFHRm36GhnURYvpGKft

Ada 1 transaksi transfer 506 ARA tapi muncul seperti 2 transaksi pada blok 683930 dan 683931, blok 683930 kemungkinan merupakan uncle block sehingga tidak difinalisasi oleh GRANDPA dan tidak menjadi canonical, walaupun hal ini wajar dan ini tidak berimbas pada hasil akhirnya (tidak terjadi double spending) tetapi tampilan history perlu diperbaiki agar tidak perlu menampilkan transaksi dobel.

Bounty value: 
700 ARA

**Comment by anvie** [comment]
Ini mungkin bisa disolve dengan dua cara:

1. Mengganti primary key index-nya dari nomor block menjadi `account id + nonce`, atau
2. Jangan tampilkan block yg tidak canonical.

**Comment by rzfn** [comment]
Aku ambil kalo belum ada prioritas lain
